import type { Metadata } from "next";
import "./globals.css";
import type { FC, ReactNode } from "react";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className="d-flex justify-content-center align-items-center vh-100">{children}</body>
    </html>
  );
};

export default RootLayout;
