import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import type { FC, ReactNode } from "react";
import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className="d-flex justify-content-center align-items-center vh-100">{children}</body>
    </html>
  );
};

export default RootLayout;

